############################################################
#
# web访问端口号  约定：8066
#
############################################################
server:
  port: 8066
  tomcat:
    uri-encoding: UTF-8


############################################################
#
# fdfs 配置
#
############################################################
fdfs:
  connect-timeout: 30   # 连接的超时时间
  so-timeout: 30        # 读取的超时时间
  tracker-list: 192.144.191.163:22122   # tracker服务所在的ip地址和端口号
